"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$git_branch$git_status$git_state$cmd_duration
$character"""

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
