#!/usr/bin/env fish
#MISE description="Prune broken symlinks in home directory pointing to the dotfiles repository"

set broken_symlinks (find -L "$HOME" -type l 2>/dev/null)
for broken_symlink in $broken_symlinks
	set target (readlink -f "$broken_symlink")
	if not string match -q "$MISE_PROJECT_ROOT/*" "$target"
		continue
	end
	echo "Delete broken symlink: $broken_symlink ➜ $target"
	read -P '[y/n]: ' confirm_delete
	if test "$confirm_delete" = "y"
		rm "$broken_symlink"
	end
end
