[env]
MISE_FISH_AUTO_ACTIVATE = 0

[settings]
experimental = true

[tools]
gradle = "8"
java = "temurin-21"
kotlin = "2"
node = "20"
"npm:cdktf-cli" = "0.20.11"
rust = "1"
terraform = "1"
"ubi:jkemming/keexp" = "latest"
"ubi:starship/starship" = "1"
